- name: Install Nginx and Certbot
  apt:
    name: [nginx, certbot, python3-certbot-nginx]
    state: present

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: Deploy Nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/scenario-lab
  notify: Reload Nginx

- name: Enable site
  file:
    src: /etc/nginx/sites-available/scenario-lab
    dest: /etc/nginx/sites-enabled/scenario-lab
    state: link
  notify: Reload Nginx

- name: Obtain TLS certificate
  command: >
    certbot --nginx -d {{ domain }}
    --non-interactive --agree-tos -m {{ admin_email }}
  args:
    creates: /etc/letsencrypt/live/{{ domain }}
  ignore_errors: true # Allowing no TLS certificate for now.
